# .github/workflows/e2e_tests.yml
name: End-to-End Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 3 * * 1'  # Weekly Monday 3 AM

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
      WHATSAPP_PHONE_ID: ${{ secrets.WHATSAPP_PHONE_ID }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run E2E Tests
      run: |
        echo "🚀 Running End-to-End Tests for Phases 1-3"
        python tests/test_e2e_complete.py
        
    - name: Run Pytest Version
      run: |
        # Also run with pytest for detailed reporting
        python -m pytest tests/test_e2e_complete.py -v -s --tb=short || true
    
    - name: Cleanup Test Data
      if: always()
      run: |
        python -c "
from tests.test_e2e_complete import RefiloeE2ETester
tester = RefiloeE2ETester()
tester.cleanup_test_data()
        " || echo "Cleanup done"
