name: Integration Tests

on:
  workflow_dispatch:  # Manual trigger only to save API costs
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL || secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.TEST_SUPABASE_SERVICE_KEY || secrets.SUPABASE_SERVICE_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run integration tests
      run: |
        python -m pytest tests/test_integration_real.py -v -s
    
    - name: Cleanup test data
      if: always()
      run: |
        python tests/cleanup_test_data.py || true
