name: Update Supabase Types (on migration PRs)

on:
  pull_request:
    paths:
      - 'supabase/migrations/**'  # only run if a migration file changes

jobs:
  update-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Generate Supabase types
        run: |
          supabase gen types typescript --project-id ${{ secrets.SUPABASE_URL }} \
            --db-url "postgresql://postgres:${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}@db.${{ secrets.SUPABASE_URL#https://}}/postgres" \
            > src/types/supabase.ts

      - name: Commit updated types to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Supabase types"
          branch: ${{ github.head_ref }}
          push_options: --force
